apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: quay.io/jezhu/observability-operator
  newTag: 0.4.0-dev-0.4.0
commonAnnotations:
  package-operator.run/phase: operator
resources:
- ../../operator/
